### ISSUE TITLE
Writer removed after updating Metadata upon rescan

### ISSUE THREAD

**Issue by BagratAbramian** [Kareadita/Kavita#1430]
**To Reproduce**
1. Open a Series;
2. Click on 'Edit Series information';
3. Click on the 'People' tab;
4. Update the 'Writer' field;
5. Click 'Save';
6. Click on 'Edit Series information';
7. Click on the 'Metadata' tab;
8. Edit any of the fields of 'Metadata' tab (add, remove, or modify the field);
9. Click Save;
10. Either select 'Scan Series' on the series, scan the library which contains the series from the library ifself, scan the library from the 'Server Settings'' 'Libraries' tab, or wait for an automated library scan to occur;
11. The 'Writer' field will be blank, and checking the writer's works from another work will not return the work among them; if it was the only work tagged with that writer, the author will no longer be recognized and will have to be added again.

**Expected behavior**
The 'Writer' information should not be removed upon modification of the metadata.

**Desktop (please complete the following information):**
 - Windows 10
 - Google Chrome
 - 0.5.4.0

**Additional context**
When updating the 'Metadata' and 'Writer' simultaneously (without clicking 'Save' in between) the issue doesn't seem to occur.

**Comment by majora2007** [comment]
This is already fixed in the nightlies, v0.4.5.12. It will be available in the next stable.

**Comment by skittles9823** [comment]
This issue seems to still exist in the current nightlies, Any series I've added people metadata in gets removed upon the series getting updated during a scan.
