### ISSUE TITLE
Collections: Series have wrong cover after scrolling

### ISSUE THREAD

**Issue by ocgineer** [Kareadita/Kavita#1464]
**Describe the bug**

 Scrolling though a larger collection of series will cause the cover to duplicate and be incorrect on the series.

Having a few collections that have more than 4 rows of series, on a 1080p monitor with latest Chrome.
Once scrolling down the issue appears causing the cover to jump around and even duplicate visually thus harder to navigate the collection.

**To Reproduce**
1. Have a fairly large collection, I would say > 55 for a 1080p monitor.
4. Open the collection, observe the set image at the top being correctly shown.
5. Scroll down the collection, once you go past like row 4-5 (44/50) it will jump and covers will shift.

This also happens on Chrome mobile on iOS.

**Expected behavior**
Set image loads correctly and covers stay on the right series when navigating the collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/12483966/186068340-1dcbda49-abdd-4822-8d2a-224d3e0a9016.png)
![image](https://user-images.githubusercontent.com/12483966/186068392-819b8d9a-7c81-4e2e-9ecf-0ee3d1aa112f.png)

**Desktop (please complete the following information):**
 - OS: Docker Unraid stable
 - Browser Chrome on Windows
 - Version 0.5.5.1 stable and nightly 0.5.5.9

**Additional context**
This only happens in the collections, not when scrolling down a big library.

**Comment by majora2007** [comment]
First please keep each issue related to one bug. You have multiple listed here which adds complications when managing them. 

Collections cover images are already fixed in the nightlies. I'm pretty sure the cover image duplication is fixed as well on nightlies, but I will validate and update this ticket.

**Comment by ocgineer** [comment]
Sorry, was late at night when I did this, I removed the collection image not showing as it seems to be resolved in the latest nightly indeed. However, the scrolling issue is still present for me on the current nightly so I'll keep this open.
