### ISSUE TITLE
Unable to scroll to the next / previous chapter for short webtoons

### ISSUE THREAD

**Issue by TheIceCreamTroll** [Kareadita/Kavita#1590]
**Describe the bug**
If a webtoon isn't long enough to require a scrollbar be generated, you will not be able to turn to scrollwheel to go to the next / previous chapters

**To Reproduce**
1. Open a very short webtoon and make sure there isn't a scrollbar
2. Switch the reading mode to continuous scrolling
3. Scroll in either direction
4. The "Scroll to next / previous chapter" message should not appear

**Expected behavior**
You should always be able to scroll to go to the next / previous page, no matter the chapter length.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Firefox
 - Version 0.5.6.29

**Additional context**
Here's a test file. Copy the images to increase the page length
[Kavita Testing Ch. 1.zip](https://github.com/Kareadita/Kavita/files/9810216/Kavita.Testing.Ch.1.zip)

**Comment by majora2007** [comment]
This issue is fixed in latest code, let me know if not.

**Comment by TheIceCreamTroll** [comment]
Still seeing this issue with the included test file on 0.7.1.12

**Comment by duplaja** [comment]
Just leaving a comment that this happens when the final image in a chapter is short as well. 

core.mjs:10132 ERROR TypeError: Cannot read properties of undefined (reading 'getPageAmount')
    at s.nextPage (manga-reader.component.ts:1134:53)
    at s.handleKeyPress (manga-reader.component.ts:648:16)
    at manga-reader.component.ts:104:14
    at mm (core.mjs:15652:16)
    at c (core.mjs:15685:22)
    at platform-browser.mjs:666:17
    at v.invokeTask (zone.js:402:31)
    at Object.onInvokeTask (core.mjs:26095:33)
    at v.invokeTask (zone.js:401:60)
    at L.runTask (zone.js:171:47)

If you use the arrow key to force it to advance, rather than the menu, then it goes to a black screen with a loading symbol, and you must back-out and re-enter the story for it to work (Chrome browser, laptop)
