### ISSUE TITLE
Fit to width not working

### ISSUE THREAD

**Issue by TheSelox** [Kareadita/Kavita#2050]
**Describe the bug**
Since the update to 0.7.3 the fit to width feature in my mobile browsers does not work anymore. 
Whenever I open any comic or manga it just shows its original resolution which means I can only see a tiny part of the image. Image scaling to width is set, but does not work. 
Also I can't zoom out so reading a page is not really convenient. 
The only thing that kind of works is switching to fit to height but then I have to scroll horizontally and some part is still cut off at the bottom. 

**Screenshots**
![Screenshot_20230610-001351](https://github.com/Kareadita/Kavita/assets/91619275/f9127139-55d8-4243-9321-809af5692553)
![Screenshot_20230610-001338](https://github.com/Kareadita/Kavita/assets/91619275/95f94cf9-3871-49aa-bdc3-e6fc1891bc0d)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6
 - OS: Android 13
 - Browser: Firefox beta and Chrome (both latest version) 

**Additional context**
First I thought it could be an issue with Firefox but then I tried it in chrome and I've never used it on this phone before to log into Kavita and read comics.

**Comment by krsuhjunho** [comment]
The problem appears to occur when the width of the responsive canvas in the browser is less than 565.

I am using an iPhone 13 mini and can confirm that the same issue occurs.

In 0.7.3, it was displaying fine with no issues.

**Comment by krsuhjunho** [comment]
I think the problem is that in commit #2032, .full-width { width: 100%; was deleted from width: 100%;, and this is the history.

I found that adding fit-to-screen using developer tooling or adding width 100% from full-width solved the problem.

`class="full-width ng-star-inserted"` 

to 

`class="fit-to-screen full-width ng-star-inserted"` 

or 

    margin: 0 auto;
    vertical-align: top;
    max-width: -moz-fit-content;
    max-width: fit-content;
    **width: 100%;**
}

Few More Fixes (https://github.com/Kareadita/Kavita/pull/2032)
`UI/Web/src/_manga-reader-common.scss


Thank you

**Comment by majora2007** [comment]
I suspected that as well, but that line causes stretching on desktops when a full width is present. 

I tested it with responsive windows, but it looks like I needed to use a phone.

**Comment by majora2007** [comment]
Okay, I understand the bug. It's not the fit to width for spreads, it's just width scaling is failing. I wonder how no one caught this before the release. I'll issue a hotfix.

**Comment by TheSelox** [comment]
@majora2007 hey I'm sorry, but I updated to the latest release and nothing changed for me regarding this issue.
I tried it again in Firefox and Chrome after updating to 0.7.3.1 (and confirming the version).

**Comment by majora2007** [comment]
Then I'm not sure what the issue you're facing is. Is this a spread or a regular page? Can you do a head refresh?

**Comment by TheSelox** [comment]
How do I do that?
I already deleted cookies and site data.

**Comment by TheSelox** [comment]
Btw it's a regular page. Doesn't matter which comic I open.
In this screenshot you can see how it should approximately look like because I changed it to fit to height. It's still a bit cut off at the bottom though. 
![Screenshot_20230610-225357](https://github.com/Kareadita/Kavita/assets/91619275/d06f38d0-a00b-4325-bea4-ca9381bcf080)

**Comment by majora2007** [comment]
Hmm, i'm not able to reproduce. I tested on my Fire HD 10 before I released the hotfix. Scaling was working on every page. I wonder if this is somehow an edge case on this screen size? I just tested on my phone as well and it's working fine. 

@therobbiedavis would you be able to test and see if you can reproduce?

**Comment by scare376** [comment]
I noticed this issue as well at the same time this was reported. Im on a pixel 6 pro and it seems to be working correctly now.

**Comment by sosoforall** [comment]
I am still facing this issue for all the devices I have regardless of OS and browsers (ios, android, mac os, and windows). I'm using the docker image, kizaing/kavita:latest.

**Comment by TheSelox** [comment]
I guess I can reproduce it in my desktop browser if I make the width of the window small enough.

![grafik](https://github.com/Kareadita/Kavita/assets/91619275/f9b03a2b-d80f-4460-aa49-89c66cfeb4c6)

When I manually set the container image to 0.7.2 everything works again.

![grafik](https://github.com/Kareadita/Kavita/assets/91619275/8141d4c9-bd39-44e9-814c-d917faa24782)

**Comment by arb362** [comment]
I'm having the same issue on a Samsung Galaxy Tablet. Im also running the latest version via docker.

**Comment by Oniicode** [comment]
I can confirm that in 0.7.3.1, i have this issue on my Xiaomi Mi 8 (Android 12, Chrome 114.0.5735.60) as well as on Desktop the way @TheSelox mentioned. 

Interestingly, it also happens on my Galaxy **Tab** S5e (also Android 12, same Chrome version). 
![Screenshot_20230612-215403_Chrome](https://github.com/Kareadita/Kavita/assets/46069626/20441d16-1b6e-45b6-9cf3-045f95c2f7e2)
Height Scaling mode works somewhat fine on it tho. Requires me 1 cm of scrolling to fit it entirely on the screen, but otherwise fully usable.
![Screenshot_20230612-215834_Chrome](https://github.com/Kareadita/Kavita/assets/46069626/0a363f19-3cf0-46dd-9717-7b7693c54e6f)


To all users on Android, i can recommend my workaround of just using [Tachiyomi](https://github.com/tachiyomiorg/tachiyomi) with its own kavita source extension, which comes with it's own native reader.

**Comment by Oniicode** [comment]
Update: I found a workaround.
By appending the following CSS code to the end of my custom theme, everything works fine again:

```
@media (max-width: 900px){
        .image-container.full-width img {
                width: 100% !important;
        }
}
```

It's the same as the CSS by @krsuhjunho except it's applied to only the img, not the .full-width div containing it.
The img already seems to have `max-width: fit-content`, but it doesn't seem to have any effect at all (I toggled the property on and off in devtools)

For anyone else interested in trying this workaround, see [this article](https://wiki.kavitareader.com/en/guides/settings/themes) on how to set up a custom theme.

@majora2007 
> [...], but that line causes stretching on desktops when a full width is present.

I added the media query just in case for that. I chose the smallest width for it at which i can't observe the bug anymore.
And that value (900px) coicidentally ended up being exactly the same as the width of my actual manga page in the archive.
So in the end, i ditched the media query and left it as a one liner,
`.image-container.full-width img { width: 100% !important; }`

**Comment by TheSelox** [comment]
@Oniicode thank you, that seemed to work.

**Comment by random-human-being** [comment]
Same issue for me Android, after updating my server from 7.1 to 7.3. The browser is Firefox 114.1.1 on Galaxy M31.

Webcomic mode fits the image to the display's width just fine though.

**Comment by RealStickman** [comment]
Testing on my desktop, the problem seems to occur when the browser window is less wide than the manga page.  
For that reason, I used the aspect ratio instead of pixel width in my solution.  

Also, keep the css for this outside the normal theme class. I struggled way too long with this until it clicked.  
```
:root .bg-your-theme {
  /* theme stuff */
}
  /* work around issue where fit to width is too wide
   * based on aspect ratio of screen instead of fixed pixel amount
   * https://github.com/Kareadita/Kavita/issues/2050 */
@media (max-aspect-ratio: 9/10) {
  .image-container.full-width img {
    width: 100% !important;
  }
}
```

**Comment by majora2007** [comment]
Is anyone here experiencing on a non-docker based server? I'm starting to believe the hotfix didn't push correctly

**Comment by scare376** [comment]
Loaded up 0.7.3.1 on barebones windows and fit to width does work properly.

**Comment by majora2007** [comment]
This explains why I can't reproduce it. The docker build must not have actually pushed the hot fix out. 

I will make a post, the next release isn't too far out.
