### ISSUE TITLE
[Bug] Book Reader - Touching tap pagination zones with the book settings menu open turns pages

### ISSUE THREAD

**Issue by Hobogrammer** [Kareadita/Kavita#2430]
**Describe the bug**
While reading a book if you open the book settings menu and click anywhere the tap pagination zones are set to the page will be turned. This occurs even if turn pagination is disabled.

**To Reproduce**
1. Open a book and note the current virtual page
2. Click the menu button to open the book settings
3. Click in an area on the book settings menu that is inside of the left tap pagination area.
4. Notice that the page has been turned
5.  Do the same but on the right side.
6. Notice the page has been changed.

**Expected behavior**
Page should remain the same when clicking in tap pagination zones when the book settings menu is open.

**Server:**
 - OS: Docker
 - Version: 0.7.10.8
 
**Desktop :**
 - OS: Windows 10
 - Browser: firefox

**Client device :**
 - Device: Boox Page
 - OS: Android 11
 - Browser: Kiwibrowser, firefox
 
**Additional context**
Clicking in a non pagination zones doesn't change the page. Happens with all layout types, reading directions, and writing styles.

**Comment by majora2007** [comment]
This is already fixed on the latest nightly. Please update.

**Comment by majora2007** [comment]
v0.7.10.10 fixed it:
> Fixed: Fixed a bug in nightly where clicking on menu/actionbar could trigger pagination in the epub reader

**Comment by majora2007** [comment]
Fixed this just today in the latest nightly.

**Comment by Hobogrammer** [comment]
I'm still experiencing page turns when attempting to dismiss the settings menu by clicking on the right side.

Version 0.7.10.13
