### ISSUE TITLE
Next Chapter API throwing 500 error and skipping place in book

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2613]
### What happened?

I'm not sure if these events are linked, but I have a series that when it hits what should be the last page in a series, it will jump to a spot looped back around in volume 1 again.

```
[Kavita] [2024-01-10 00:04:14.231 -05:00  111] [Information] API.Controllers.ReaderController Fetching Page 32 on Chapter 328917
[Kavita] [2024-01-10 00:04:14.232 -05:00  111] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=328917&apiKey=******REDACTED******&page=32" responded 200 in 3.0374 ms
[Kavita] [2024-01-10 00:04:14.301 -05:00  119] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 72.2767 ms
[Kavita] [2024-01-10 00:04:14.305 -05:00  111] [Information] API.Services.Plus.ScrobblingService Processing Scrobbling reading event for 1 on Ijiranaide, Nagatoro-san
[Kavita] [2024-01-10 00:04:14.366 -05:00  111] [Debug] API.Services.Plus.ScrobblingService Added Scrobbling Read update on Ijiranaide, Nagatoro-san with Userid 1 
[Kavita] [2024-01-10 00:04:15.224 -05:00  111] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 0.9834 ms
[Kavita] [2024-01-10 00:04:15.225 -05:00  123] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/chapter-bookmarks?chapterId=228624 responded 200 in 0.9586 ms
[Kavita] [2024-01-10 00:04:15.225 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/get-progress?chapterId=228624 responded 200 in 1.3082 ms
[Kavita] [2024-01-10 00:04:15.833 -05:00  119] [Debug] API.Services.CacheService File Dimensions call for 162 images took 602ms
[Kavita] [2024-01-10 00:04:15.834 -05:00  119] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/chapter-info?chapterId=228624&includeDimensions=true responded 200 in 609.0484 ms
[Kavita] [2024-01-10 00:04:16.042 -05:00  111] [Information] API.Controllers.ReaderController Fetching Page 162 on Chapter 228624
[Kavita] [2024-01-10 00:04:16.043 -05:00  119] [Information] API.Controllers.ReaderController Fetching Page 161 on Chapter 228624
```

You can see it went to page 32, which is the last page in the book. When I hit the right arrow key on the keyboard it went and loaded volume 1 but it dropped me in at page 162. 

```
[Kavita] [2024-01-10 00:04:18.432 -05:00  123] [Error] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/next-chapter?seriesId=10532&volumeId=24719&currentChapterId=228624 responded 500 in 8.0152 ms
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at API.Services.ReaderService.GetNextChapterIdAsync(Int32 seriesId, Int32 volumeId, Int32 currentChapterId, Int32 userId) in /home/runner/work/Kavita/Kavita/API/Services/ReaderService.cs:line 366
   at API.Controllers.ReaderController.GetNextChapter(Int32 seriesId, Int32 volumeId, Int32 currentChapterId) in /home/runner/work/Kavita/Kavita/API/Controllers/ReaderController.cs:line 776
   at lambda_method5872(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 363
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
```

### What did you expect?

When you reach the end of a series it should say "no more pages left" 

### Version

0.7.12.3 - Nightly

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Chrome

### Additional Notes

Can be pretty reliably recreated on /library/2/series/10532 on my host.

**Comment by DieselTech** [comment]
Here's a bit of the logs around when skipping is going on. 

Chapter ID 340141 was the chapter being read at the time. 

Right when I finished reading page 23 of 26, it started preloading another chapter (228624) 

It should of stopped at chapter ID 340141, as there is nothing else past this point. 

```
[Kavita] [2024-01-22 13:47:51.763 -05:00  79] [Information] API.Controllers.ReaderController Fetching Page 20 on Chapter 340141
[Kavita] [2024-01-22 13:47:51.780 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=20" responded 200 in 18.7801 ms
[Kavita] [2024-01-22 13:47:51.840 -05:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 78.5460 ms
[Kavita] [2024-01-22 13:47:56.442 -05:00  79] [Information] API.Controllers.ReaderController Fetching Page 21 on Chapter 340141
[Kavita] [2024-01-22 13:47:56.467 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=21" responded 200 in 27.4958 ms
[Kavita] [2024-01-22 13:47:56.514 -05:00  86] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 78.2308 ms
[Kavita] [2024-01-22 13:48:01.066 -05:00  86] [Information] API.Controllers.ReaderController Fetching Page 22 on Chapter 340141
[Kavita] [2024-01-22 13:48:01.083 -05:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=22" responded 200 in 19.1370 ms
[Kavita] [2024-01-22 13:48:01.160 -05:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 95.8881 ms
[Kavita] [2024-01-22 13:48:07.706 -05:00  86] [Information] API.Controllers.ReaderController Fetching Page 23 on Chapter 340141
[Kavita] [2024-01-22 13:48:07.713 -05:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/chapter-info?chapterId=228624&includeDimensions=false responded 200 in 12.9305 ms
[Kavita] [2024-01-22 13:48:07.730 -05:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=23" responded 200 in 25.8830 ms
[Kavita] [2024-01-22 13:48:07.773 -05:00  85] [Information] API.Controllers.ReaderController Fetching Page 1 on Chapter 228624
[Kavita] [2024-01-22 13:48:07.774 -05:00  88] [Information] API.Controllers.ReaderController Fetching Page 3 on Chapter 228624
[Kavita] [2024-01-22 13:48:07.775 -05:00  87] [Information] API.Controllers.ReaderController Fetching Page 0 on Chapter 228624
[Kavita] [2024-01-22 13:48:07.850 -05:00  79] [Information] API.Controllers.ReaderController Fetching Page 2 on Chapter 228624
[Kavita] [2024-01-22 13:48:07.850 -05:00  88] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=228624&apiKey=******REDACTED******&page=3" responded 304 in 79.1938 ms
[Kavita] [2024-01-22 13:48:07.851 -05:00  87] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=228624&apiKey=******REDACTED******&page=0" responded 304 in 79.6555 ms
[Kavita] [2024-01-22 13:48:07.851 -05:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=228624&apiKey=******REDACTED******&page=1" responded 304 in 80.0183 ms
[Kavita] [2024-01-22 13:48:07.856 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=228624&apiKey=******REDACTED******&page=2" responded 304 in 85.0054 ms
[Kavita] [2024-01-22 13:48:07.922 -05:00  85] [Information] API.Controllers.ReaderController Fetching Page 4 on Chapter 228624
[Kavita] [2024-01-22 13:48:07.924 -05:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=228624&apiKey=******REDACTED******&page=4" responded 304 in 3.7105 ms
[Kavita] [2024-01-22 13:48:07.936 -05:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 231.8227 ms
[Kavita] [2024-01-22 13:48:14.999 -05:00  88] [Information] API.Controllers.ReaderController Fetching Page 24 on Chapter 340141
[Kavita] [2024-01-22 13:48:15.030 -05:00  88] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=24" responded 200 in 32.6861 ms
[Kavita] [2024-01-22 13:48:15.075 -05:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 81.8022 ms
[Kavita] [2024-01-22 13:48:30.930 -05:00  81] [Information] API.Controllers.ReaderController Fetching Page 25 on Chapter 340141
[Kavita] [2024-01-22 13:48:30.938 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=25" responded 200 in 9.1530 ms
[Kavita] [2024-01-22 13:48:31.137 -05:00  88] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 210.8954 ms
[Kavita] [2024-01-22 13:48:37.712 -05:00  88] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 220.8630 ms
[Kavita] [2024-01-22 13:48:45.025 -05:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 104.1852 ms
[Kavita] [2024-01-22 13:48:50.795 -05:00  88] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 71.7068 ms
[Kavita] [2024-01-22 13:48:58.555 -05:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 200.3736 ms
[Kavita] [2024-01-22 13:49:02.762 -05:00  8] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 197.7494 ms
[Kavita] [2024-01-22 13:49:09.827 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 109.2480 ms
[Kavita] [2024-01-22 13:49:13.070 -05:00  8] [Information] API.Controllers.ReaderController Fetching Page 26 on Chapter 340141
[Kavita] [2024-01-22 13:49:13.077 -05:00  79] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=340141&apiKey=******REDACTED******&page=26" responded 200 in 9.0914 ms
[Kavita] [2024-01-22 13:49:13.261 -05:00  85] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 192.0810 ms
[Kavita] [2024-01-22 13:49:13.268 -05:00  88] [Information] API.Services.Plus.ScrobblingService Processing Scrobbling reading event for 1 on Ijiranaide, Nagatoro-san
[Kavita] [2024-01-22 13:49:13.464 -05:00  88] [Debug] API.Services.Plus.ScrobblingService Added Scrobbling Read update on Ijiranaide, Nagatoro-san with Userid 1 
```

**Comment by majora2007** [comment]
I need to understand the volume and chapters that are causing this. Are you reading from the last chapter and then looping back to a single Volume (volume 1 with just a volume file)?

**Comment by DieselTech** [comment]
> I need to understand the volume and chapters that are causing this. Are you reading from the last chapter and then looping back to a single Volume (volume 1 with just a volume file)?

Yes, it occurs when reading chapters at the end of a series that it loops me back to a volume that is at the beginning of the series. 

The logs show me reading chapter 143 which is chapter ID 340141. When I reach the last page in that chapter, it will send me back around to Volume 1 (ID 228624) again. It says it's getting page 1 of ID 228624, but it's really sending me to like page 160 of 163

**Comment by majora2007** [comment]
Hmm I can reproduce this on /library/2/series/10532 but I have the exact same series and file layout and it works on my local. It might have been fixed as I changed some code around volume matching.

**Comment by majora2007** [comment]
Please try on the latest nightly (v0.7.13.8). This should be fixed.

**Comment by DieselTech** [comment]
Nope, still occurring. Wasn't that exact series this time, but `library/2/series/300` 

![image](https://github.com/Kareadita/Kavita/assets/30128380/1199c527-a11a-4482-92ad-9566f52853ad)

**Comment by DieselTech** [comment]
Here is the logs from this current session where it still jumped to the first volume in the series.

343710 is the new chapter that was being read. 

You can see it starts to pre-load images from chapter 9233 

Also this part stood out as not right `[Kavita] [2024-01-28 14:09:35.312 -05:00  63] [Information] API.Controllers.ReaderController Fetching Page 1000000 on Chapter 339942` 


```
[Kavita] [2024-01-28 14:09:35.236 -05:00  60] [Information] API.Controllers.ReaderController Fetching Page 4 on Chapter 343710
[Kavita] [2024-01-28 14:09:35.236 -05:00  62] [Information] API.Controllers.ReaderController Fetching Page 3 on Chapter 343710
[Kavita] [2024-01-28 14:09:35.241 -05:00  65] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=0" responded 200 in 55.4634 ms
[Kavita] [2024-01-28 14:09:35.245 -05:00  65] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=1" responded 200 in 58.9143 ms
[Kavita] [2024-01-28 14:09:35.251 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 55.5498 ms
[Kavita] [2024-01-28 14:09:35.260 -05:00  56] [Information] API.Controllers.ReaderController Fetching Page 5 on Chapter 343710
[Kavita] [2024-01-28 14:09:35.261 -05:00  60] [Information] API.Controllers.ReaderController Fetching Page 6 on Chapter 343710
[Kavita] [2024-01-28 14:09:35.270 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=3" responded 200 in 36.0745 ms
[Kavita] [2024-01-28 14:09:35.275 -05:00  63] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=4" responded 200 in 40.6565 ms
[Kavita] [2024-01-28 14:09:35.285 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=6" responded 200 in 25.8602 ms
[Kavita] [2024-01-28 14:09:35.289 -05:00  52] [Information] API.Controllers.ReaderController Fetching Page 7 on Chapter 343710
[Kavita] [2024-01-28 14:09:35.307 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=5" responded 200 in 48.9596 ms
[Kavita] [2024-01-28 14:09:35.311 -05:00  63] [Debug] API.Services.ArchiveService Extracted archive to /kavita/config/cache/339942/ in 18 milliseconds
[Kavita] [2024-01-28 14:09:35.312 -05:00  63] [Information] API.Controllers.ReaderController Fetching Page 1000000 on Chapter 339942
[Kavita] [2024-01-28 14:09:35.314 -05:00  63] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=339942&apiKey=******REDACTED******&page=1000000" responded 200 in 27.0140 ms
[Kavita] [2024-01-28 14:09:35.316 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=7" responded 200 in 29.0387 ms
[Kavita] [2024-01-28 14:09:37.550 -05:00  60] [Debug] API.Services.ArchiveService Extracted archive to /kavita/config/cache/9233/ in 2260 milliseconds
[Kavita] [2024-01-28 14:09:37.551 -05:00  60] [Information] API.Controllers.ReaderController Fetching Page 0 on Chapter 9233
[Kavita] [2024-01-28 14:09:37.567 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=9233&apiKey=******REDACTED******&page=0" responded 200 in 2279.9927 ms
[Kavita] [2024-01-28 14:09:51.771 -05:00  60] [Information] API.Controllers.ReaderController Fetching Page 8 on Chapter 343710
[Kavita] [2024-01-28 14:09:51.777 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/chapter-info?chapterId=339942&includeDimensions=false responded 200 in 7.5164 ms
[Kavita] [2024-01-28 14:09:51.788 -05:00  60] [Information] API.Controllers.ReaderController Fetching Page 1 on Chapter 9233
[Kavita] [2024-01-28 14:09:51.791 -05:00  56] [Information] API.Controllers.ReaderController Fetching Page 3 on Chapter 9233
[Kavita] [2024-01-28 14:09:51.793 -05:00  52] [Information] API.Controllers.ReaderController Fetching Page 2 on Chapter 9233
[Kavita] [2024-01-28 14:09:51.796 -05:00  60] [Information] API.Controllers.ReaderController Fetching Page 4 on Chapter 9233
[Kavita] [2024-01-28 14:09:51.808 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=8" responded 200 in 39.2930 ms
[Kavita] [2024-01-28 14:09:51.812 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=9233&apiKey=******REDACTED******&page=2" responded 200 in 24.9529 ms
[Kavita] [2024-01-28 14:09:51.817 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=9233&apiKey=******REDACTED******&page=1" responded 200 in 31.5558 ms
[Kavita] [2024-01-28 14:09:51.822 -05:00  52] [Information] API.Controllers.ReaderController Fetching Page 5 on Chapter 9233
[Kavita] [2024-01-28 14:09:51.866 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=9233&apiKey=******REDACTED******&page=4" responded 200 in 71.5356 ms
[Kavita] [2024-01-28 14:09:51.873 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=9233&apiKey=******REDACTED******&page=5" responded 200 in 52.8188 ms
[Kavita] [2024-01-28 14:09:51.891 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=9233&apiKey=******REDACTED******&page=3" responded 200 in 101.9150 ms
[Kavita] [2024-01-28 14:09:52.201 -05:00  63] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 432.1340 ms
[Kavita] [2024-01-28 14:10:00.434 -05:00  52] [Information] API.Controllers.ReaderController Fetching Page 9 on Chapter 343710
[Kavita] [2024-01-28 14:10:00.455 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=9" responded 200 in 22.7890 ms
[Kavita] [2024-01-28 14:10:00.642 -05:00  63] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 208.7633 ms
[Kavita] [2024-01-28 14:10:20.396 -05:00  52] [Information] API.Controllers.ReaderController Fetching Page 10 on Chapter 343710
[Kavita] [2024-01-28 14:10:20.402 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/chapter-info?chapterId=9233&includeDimensions=false responded 200 in 8.6676 ms
[Kavita] [2024-01-28 14:10:20.417 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=10" responded 200 in 23.5115 ms
[Kavita] [2024-01-28 14:10:20.610 -05:00  63] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 216.5664 ms
[Kavita] [2024-01-28 14:10:30.565 -05:00  63] [Information] API.Controllers.ReaderController Fetching Page 11 on Chapter 343710
[Kavita] [2024-01-28 14:10:30.586 -05:00  63] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=11" responded 200 in 21.7967 ms
[Kavita] [2024-01-28 14:10:30.808 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 243.6904 ms
[Kavita] [2024-01-28 14:10:41.873 -05:00  56] [Information] API.Controllers.ReaderController Fetching Page 12 on Chapter 343710
[Kavita] [2024-01-28 14:10:41.886 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=12" responded 200 in 14.6891 ms
[Kavita] [2024-01-28 14:10:42.031 -05:00  52] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 162.4350 ms
[Kavita] [2024-01-28 14:10:45.929 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 257.7887 ms
[Kavita] [2024-01-28 14:10:50.635 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 235.4812 ms
[Kavita] [2024-01-28 14:10:53.151 -05:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 73.0481 ms
[Kavita] [2024-01-28 14:11:10.355 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 191.8246 ms
[Kavita] [2024-01-28 14:11:19.429 -05:00  69] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/refresh-token responded 200 in 360.3160 ms
[Kavita] [2024-01-28 14:11:19.520 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 3.2333 ms
[Kavita] [2024-01-28 14:11:19.619 -05:00  68] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 0.6636 ms
[Kavita] [2024-01-28 14:11:19.629 -05:00  68] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.3108 ms
[Kavita] [2024-01-28 14:11:24.809 -05:00  68] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 91.6909 ms
[Kavita] [2024-01-28 14:11:36.007 -05:00  69] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 147.0794 ms
[Kavita] [2024-01-28 14:11:41.822 -05:00  69] [Information] API.Controllers.ReaderController Fetching Page 13 on Chapter 343710
[Kavita] [2024-01-28 14:11:41.834 -05:00  56] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET "/api/reader/image?chapterId=343710&apiKey=******REDACTED******&page=13" responded 200 in 14.0732 ms
[Kavita] [2024-01-28 14:11:42.050 -05:00  68] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/reader/progress responded 200 in 226.8224 ms
[Kavita] [2024-01-28 14:11:42.058 -05:00  56] [Information] API.Services.Plus.ScrobblingService Processing Scrobbling reading event for 1 on Uzaki-chan Wants to Hang Out!
[Kavita] [2024-01-28 14:11:42.318 -05:00  56] [Debug] API.Services.Plus.ScrobblingService Added Scrobbling Read update on Uzaki-chan Wants to Hang Out! with Userid 1 
```

**Comment by majora2007** [comment]
`API.Controllers.ReaderController Fetching Page 1000000 on Chapter 339942` is not an issue. It is per design. 

Logs don't help much. I'll keep trying to reproduce it on my local. I don't have admin on your server so I can't see the exact makeup of volume/chapters, which helps debug the issue. But I'm assuming your series you linked matches mine.

**Comment by majora2007** [comment]
This is a duplicate of https://github.com/Kareadita/Kavita/issues/2099
