### ISSUE TITLE
Kavita not scanning libraries

### ISSUE THREAD

**Issue by Cantello** [Kareadita/Kavita#2768]
### What happened?

Library scans get queued but are not actually performed, neither forced nor regular scans.

### What did you expect?

The library that is about to be scanned is scanned.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-03-08 00:00:10.404 +00:00  205] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list
[Kavita] [2024-03-08 00:00:10.801 +00:00  190] [Information] API.Services.Tasks.CleanupService Starting Cleanup
[Kavita] [2024-03-08 00:00:10.801 +00:00  55] [Information] API.Services.Tasks.ScannerService Starting Scan of All Libraries
[Kavita] [2024-03-08 00:00:10.894 +00:00  190] [Information] API.Services.Tasks.CleanupService Cleaning temp directory
[Kavita] [2024-03-08 00:00:10.895 +00:00  190] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2024-03-08 00:00:10.896 +00:00  190] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2024-03-08 00:00:10.896 +00:00  190] [Information] API.Services.Tasks.CleanupService Cleaning old database backups
[Kavita] [2024-03-08 00:00:10.909 +00:00  190] [Information] API.Services.Tasks.CleanupService Beginning cleanup of Database backups at "2024-03-08T00:00:10.9088408+00:00"
[Kavita] [2024-03-08 00:00:10.916 +00:00  190] [Information] API.Services.Tasks.CleanupService Finished cleanup of Database backups at "2024-03-08T00:00:10.9162002+00:00"
[Kavita] [2024-03-08 00:00:10.916 +00:00  190] [Information] API.Services.Tasks.CleanupService Cleaning deleted cover images
[Kavita] [2024-03-08 00:00:11.030 +00:00  205] [Warning] Microsoft.EntityFrameworkCore.Query Collection navigations are only considered null if their parent entity is null. Use 'Any' to check whether collection navigation 'Series.Progress' is empty.
[Kavita] [2024-03-08 00:00:11.068 +00:00  190] [Information] API.Services.Tasks.CleanupService Performing cleanup of logs directory
[Kavita] [2024-03-08 00:00:11.069 +00:00  190] [Information] API.Services.Tasks.CleanupService Finished cleanup of logs at "2024-03-08T00:00:11.0689825+00:00"
[Kavita] [2024-03-08 00:00:11.069 +00:00  190] [Information] API.Services.Tasks.CleanupService Cleaning up any progress rows that exceed chapter page count
[Kavita] [2024-03-08 00:00:11.088 +00:00  190] [Information] API.Services.Tasks.CleanupService Cleaning up any progress rows that exceed chapter page count - complete
[Kavita] [2024-03-08 00:00:11.102 +00:00  205] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list, completed
[Kavita] [2024-03-08 00:00:11.104 +00:00  55] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 00:00:11.355 +00:00  190] [Information] API.Services.Tasks.CleanupService Cleanup finished
[Kavita] [2024-03-08 00:00:40.294 +00:00  190] [Information] API.Services.Tasks.ScannerService Starting Scan of All Libraries
[Kavita] [2024-03-08 00:00:40.309 +00:00  190] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 00:01:25.296 +00:00  190] [Information] API.Services.Tasks.ScannerService Starting Scan of All Libraries
[Kavita] [2024-03-08 00:01:25.310 +00:00  190] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 00:02:10.298 +00:00  205] [Information] API.Services.Tasks.ScannerService Starting Scan of All Libraries
[Kavita] [2024-03-08 00:02:10.313 +00:00  205] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 02:00:10.987 +00:00  279] [Information] API.Services.Tasks.BackupService Beginning backup of Database at "2024-03-08T02:00:10.9862599+00:00"
[Kavita] [2024-03-08 02:00:11.396 +00:00  279] [Debug] API.Services.Tasks.BackupService Backing up to /kavita/config/backups
[Kavita] [2024-03-08 02:00:11.403 +00:00  279] [Error] API.Services.DirectoryService Unable to copy /kavita/config/Hangfire.db to /kavita/config/temp/03_08_2024_02_00_11 as it doesn't exist
[Kavita] [2024-03-08 02:00:11.403 +00:00  279] [Error] API.Services.DirectoryService Unable to copy /kavita/config/Hangfire-log.db to /kavita/config/temp/03_08_2024_02_00_11 as it doesn't exist
[Kavita] [2024-03-08 02:00:11.420 +00:00  279] [Error] API.Services.DirectoryService Unable to copy /kavita/config/kavita.db-shm to /kavita/config/temp/03_08_2024_02_00_11 as it doesn't exist
[Kavita] [2024-03-08 02:00:11.420 +00:00  279] [Error] API.Services.DirectoryService Unable to copy /kavita/config/kavita.db-wal to /kavita/config/temp/03_08_2024_02_00_11 as it doesn't exist
[Kavita] [2024-03-08 02:00:11.929 +00:00  279] [Information] API.Services.Tasks.BackupService Database backup completed
[Kavita] [2024-03-08 05:03:11.582 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-03-08 05:03:11.867 +00:00  6] [Fatal] API.Program Running MigrateWantToReadExport migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:11.907 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-03-08 05:03:16.432 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-03-08 05:03:16.464 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-03-08 05:03:16.929 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-03-08 05:03:16.947 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-03-08 05:03:16.977 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-03-08 05:03:17.171 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-03-08 05:03:17.292 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-03-08 05:03:17.527 +00:00  6] [Fatal] API.Program Running MigrateUserLibrarySideNavStream migration - complete. Nothing to do
[Kavita] [2024-03-08 05:03:17.541 +00:00  6] [Fatal] API.Program Running MigrateSmartFilterEncoding migration - Please be patient, this may take some time. This is not an error
[Kavita] [2024-03-08 05:03:17.566 +00:00  6] [Fatal] API.Program Running MigrateSmartFilterEncoding migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:17.589 +00:00  6] [Fatal] API.Program Running MigrateLibrariesToHaveAllFileTypes migration - Please be patient, this may take some time. This is not an error
[Kavita] [2024-03-08 05:03:17.667 +00:00  6] [Fatal] API.Program Running MigrateLibrariesToHaveAllFileTypes migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:17.677 +00:00  6] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:17.705 +00:00  6] [Fatal] API.Program Running MigrateVolumeNumber migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:17.717 +00:00  6] [Fatal] API.Program Running MigrateWantToReadImport migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:17.735 +00:00  6] [Fatal] API.Program Running MigrateManualHistory migration - Completed. This is not an error
[Kavita] [2024-03-08 05:03:18.027 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-03-08 05:03:19.194 +00:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2024-03-08 05:03:19.481 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-03-08 05:03:19.484 +00:00  1] [Information] API.Program Kavita - v0.7.14.0
[Kavita] [2024-03-08 05:03:19.572 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-03-08 05:03:19.572 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-03-08 05:03:19.572 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /kavita
[Kavita] [2024-03-08 07:21:44.041 +00:00  68] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 21.2016 ms
[Kavita] [2024-03-08 07:31:40.597 +00:00  76] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/refresh-token responded 200 in 274.0056 ms
[Kavita] [2024-03-08 07:31:40.607 +00:00  84] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.8377 ms
[Kavita] [2024-03-08 07:31:40.648 +00:00  80] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 43.6093 ms
[Kavita] [2024-03-08 07:31:40.686 +00:00  81] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 80.9228 ms
[Kavita] [2024-03-08 07:41:41.626 +00:00  98] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/refresh-token responded 200 in 112.3243 ms
[Kavita] [2024-03-08 07:41:41.636 +00:00  98] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.2931 ms
[Kavita] [2024-03-08 07:41:41.640 +00:00  103] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 4.5369 ms
[Kavita] [2024-03-08 07:41:41.644 +00:00  95] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 11.0093 ms
[Kavita] [2024-03-08 07:51:42.743 +00:00  115] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/refresh-token responded 200 in 307.1459 ms
[Kavita] [2024-03-08 07:51:42.756 +00:00  109] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 3.6732 ms
[Kavita] [2024-03-08 07:51:42.760 +00:00  115] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.4234 ms
[Kavita] [2024-03-08 07:51:42.763 +00:00  109] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 5.4660 ms
[Kavita] [2024-03-08 07:55:50.327 +00:00  126] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.4440 ms
[Kavita] [2024-03-08 07:55:50.673 +00:00  123] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /home responded 200 in 346.0356 ms
[Kavita] [2024-03-08 07:55:50.949 +00:00  127] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 1.1597 ms
[Kavita] [2024-03-08 07:55:50.952 +00:00  125] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 3.0556 ms
[Kavita] [2024-03-08 07:55:50.952 +00:00  127] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 0.8899 ms
[Kavita] [2024-03-08 07:55:50.954 +00:00  125] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.4350 ms
[Kavita] [2024-03-08 07:55:50.968 +00:00  128] [Debug] API.Controllers.LibraryController Caching libraries for library_helge
[Kavita] [2024-03-08 07:55:50.977 +00:00  118] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 30.7830 ms
[Kavita] [2024-03-08 07:55:50.977 +00:00  123] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 29.0991 ms
[Kavita] [2024-03-08 07:55:51.104 +00:00  126] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/scrobbling/token-expired?provider=1 responded 200 in 47.6396 ms
[Kavita] [2024-03-08 07:55:51.104 +00:00  118] [Debug] API.Controllers.LibraryController Caching libraries for library_helge
[Kavita] [2024-03-08 07:55:51.109 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 160.3267 ms
[Kavita] [2024-03-08 07:55:51.109 +00:00  118] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 6.8044 ms
[Kavita] [2024-03-08 07:55:51.112 +00:00  125] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/dashboard?visibleOnly=true responded 200 in 59.6764 ms
[Kavita] [2024-03-08 07:55:51.153 +00:00  127] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/sidenav?visibleOnly=true responded 200 in 166.8292 ms
[Kavita] [2024-03-08 07:55:51.332 +00:00  125] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/recently-updated-series responded 200 in 119.9821 ms
[Kavita] [2024-03-08 07:55:51.334 +00:00  118] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/on-deck?libraryId=0&pageNumber=1&pageSize=20 responded 200 in 121.6740 ms
[Kavita] [2024-03-08 07:55:51.334 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/recently-added-v2?pageNumber=1&pageSize=20 responded 200 in 120.9340 ms
[Kavita] [2024-03-08 07:55:54.903 +00:00  128] [Information] API.Services.TaskScheduler Enqueuing library scan for: 5
[Kavita] [2024-03-08 07:55:54.924 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=5&force=false responded 200 in 100.5543 ms
[Kavita] [2024-03-08 07:55:54.925 +00:00  36] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2024-03-08 07:55:54.928 +00:00  36] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2024-03-08 07:55:55.007 +00:00  126] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 07:55:56.960 +00:00  126] [Information] API.Services.TaskScheduler Enqueuing library scan for: 7
[Kavita] [2024-03-08 07:55:56.961 +00:00  126] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=7&force=false responded 200 in 2.6170 ms
[Kavita] [2024-03-08 07:55:56.962 +00:00  36] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2024-03-08 07:55:56.962 +00:00  36] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2024-03-08 07:55:57.106 +00:00  128] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics [DE]
[Kavita] [2024-03-08 07:56:35.489 +00:00  118] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 07:56:50.491 +00:00  129] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics [DE]
[Kavita] [2024-03-08 07:57:50.493 +00:00  128] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics [DE]
[Kavita] [2024-03-08 07:57:50.538 +00:00  128] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics
[Kavita] [2024-03-08 07:58:29.060 +00:00  131] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/library-types responded 200 in 5.7639 ms
[Kavita] [2024-03-08 07:58:29.162 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/name-exists?name=Comics%20[DE] responded 200 in 9.3241 ms
[Kavita] [2024-03-08 07:58:31.404 +00:00  128] [Information] API.Services.TaskScheduler A duplicate request for Library Scan on library 7 occured. Skipping
[Kavita] [2024-03-08 07:58:31.404 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan?libraryId=7&force=true responded 200 in 1.8029 ms
[Kavita] [2024-03-08 07:58:35.496 +00:00  131] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Comics [DE]
[Kavita] [2024-03-08 07:58:37.923 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.4783 ms
[Kavita] [2024-03-08 07:58:37.925 +00:00  129] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /home responded 200 in 1.6837 ms
[Kavita] [2024-03-08 07:58:38.158 +00:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 1.5262 ms
[Kavita] [2024-03-08 07:58:38.159 +00:00  130] [Debug] API.Controllers.LibraryController Caching libraries for library_helge
[Kavita] [2024-03-08 07:58:38.160 +00:00  131] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 1.0496 ms
[Kavita] [2024-03-08 07:58:38.160 +00:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 0.9761 ms
[Kavita] [2024-03-08 07:58:38.160 +00:00  135] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/theme responded 200 in 1.2461 ms
[Kavita] [2024-03-08 07:58:38.162 +00:00  130] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 3.3516 ms
[Kavita] [2024-03-08 07:58:38.172 +00:00  129] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 0.9816 ms
[Kavita] [2024-03-08 07:58:38.177 +00:00  129] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/sidenav?visibleOnly=true responded 200 in 4.1418 ms
[Kavita] [2024-03-08 07:58:38.178 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.4533 ms
[Kavita] [2024-03-08 07:58:38.276 +00:00  129] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/dashboard?visibleOnly=true responded 200 in 1.5874 ms
[Kavita] [2024-03-08 07:58:38.279 +00:00  135] [Debug] API.Controllers.LibraryController Caching libraries for library_helge
[Kavita] [2024-03-08 07:58:38.279 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/scrobbling/token-expired?provider=1 responded 200 in 1.4557 ms
[Kavita] [2024-03-08 07:58:38.280 +00:00  135] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.7963 ms
[Kavita] [2024-03-08 07:58:38.342 +00:00  129] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/on-deck?libraryId=0&pageNumber=1&pageSize=20 responded 200 in 10.6606 ms
[Kavita] [2024-03-08 07:58:38.342 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/recently-added-v2?pageNumber=1&pageSize=20 responded 200 in 10.7539 ms
[Kavita] [2024-03-08 07:58:38.342 +00:00  135] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/series/recently-updated-series responded 200 in 11.0785 ms
[Kavita] [2024-03-08 07:58:40.248 +00:00  131] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/log-levels responded 200 in 2.5478 ms
[Kavita] [2024-03-08 07:58:40.248 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/task-frequencies responded 200 in 2.5572 ms
[Kavita] [2024-03-08 07:58:40.262 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings responded 200 in 18.1183 ms
[Kavita] [2024-03-08 07:58:40.329 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/server/server-info-slim responded 200 in 5.9959 ms
[Kavita] [2024-03-08 07:58:41.450 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/log-levels responded 200 in 0.3266 ms
[Kavita] [2024-03-08 07:58:41.450 +00:00  128] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/task-frequencies responded 200 in 0.5325 ms
[Kavita] [2024-03-08 07:58:41.451 +00:00  131] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings responded 200 in 1.3899 ms
[Kavita] [2024-03-08 07:58:41.512 +00:00  131] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/server/jobs responded 200 in 13.5317 ms
```

### Additional Notes

Running Kavita on a debian machine with the dockerhub container image.
My docker-compose-yml is as follows:
```
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
        - /opt/kavita/manga:/manga
        - /opt/kavita/data:/kavita/config
        - /mnt/Stuff/:/books
    ports:
      - 5001:5000
    restart: unless-stopped
```
`/mnt` is mounted as a samba share from a NAS, `/opt` is a local folder.

**Comment by majora2007** [comment]
Thanks for splitting off in a separate issue. When you created the library in Kavita, did you navigate first to / then /mnt/Stuff? Or did you go directly to /mnt/?

If the latter, please retry by specifically going to / then mnt then stuff.

**Comment by Cantello** [comment]
Actually, I did not go to /mnt/Stuff as it was a bind mount, so I went to e.g. `/books/Comics/English`. I just added a new library with the same folder and first went to the root folder, then one folder deeper at a time. Same result, the search is queued but not actually scanned. I deleted the old library and created it anew, still no luck.

Anything else I could try or would trace logging help in this case?

**Comment by majora2007** [comment]
I don't think trace would help in this case. Hmm, strange users are having issues scanning all of the sudden. 

So just to confirm, you setup a new library and did:
1. Choose a folder
2. Navigate to /
3. Navigate to manga
4. Save

Then noticed the scan never took place? How is the underlying storage handled? Is it a local drive or network mount? Something strange must be happening (and in a weird way, as the logs indicate the scan starts then nothing afterwards).

**Comment by maximo1984** [comment]
Just tried a test of a new library with 1 series in it. As you can see in the dashboard, last scanned says never.
![Screenshot from 2024-03-08 12-41-09](https://github.com/Kareadita/Kavita/assets/40921347/766336bc-67ce-45e1-889b-53dc5d01febd)
Despite running "scan library"

**Comment by majora2007** [comment]
Can you confirm your files are not just at the root of the library? 

So you select /manga/ as library root, your files are at least within a folder form that? /manga/anything/file.cbz? 

Any loose leaf files at library root will not be scanned. Another user just now didn't understand that:
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner

**Comment by maximo1984** [comment]
![Screenshot from 2024-03-08 14-47-54](https://github.com/Kareadita/Kavita/assets/40921347/cf2b9121-04ab-4a13-b2dd-5064dc8c2088)
Yes

**Comment by Cantello** [comment]
Have now completely recreated the docker container and the problem was solved. Would be nice to know what caused it, though. I have backed up the faulty container for reference.

**Comment by majora2007** [comment]
You're the second person that has had this issue where they re-created the container and it suddenly worked...Very strange.

**Comment by maximo1984** [comment]
> Have now completely recreated the docker container and the problem was solved. Would be nice to know what caused it, though. I have backed up the faulty container for reference.

Are you able to save your db collections you made when porting over? My solution was not solved, although I thought it was. Got it working on Laptop. Still problem on desktop and doing the exact same thing that worked on laptop. My issue was a folder naming heirarchy problem there I think. But as I said, same exact naming here now.

**Comment by scare376** [comment]
As long as the config folder is intact you shouldn't lose anything. Are you using docker?

**Comment by maximo1984** [comment]
No, Ubuntu (no Docker yet though intend to get into it)

**Comment by scare376** [comment]
Maybe try moving the config folder out. start from scratch to see what happens. or just keep a copy of the config folder. delete everything else and redownload to see if that fixes it.

**Comment by maximo1984** [comment]
Ok, I will do that. Thanks.

**Comment by Cantello** [comment]
> As long as the config folder is intact you shouldn't lose anything. Are you using docker?

Yes, docker. Just stopping deleting and restarting the container did not work, I had to start from scratch. Saved the backup files, though, will see if it still works once I restore the backup.

**Comment by Cantello** [comment]
Addendum: Restoring from a recent backup did not help. Covers are refreshed but new content is not added, the libraries are not scanned.

**Comment by maximo1984** [comment]
That is unfortunate to hear. Have you checked your folder hierarchy naming conventions? Could you post a screenshot of that?

**Comment by Cantello** [comment]
> That is unfortunate to hear. Have you checked your folder hierarchy naming conventions? Could you post a screenshot of that?

The library itself is fine and it was working until a few days ago. Maybe I played around with ComicRack & tagging a little bit too much and this broke Kavita.

My folder are generally like this (above this folder is a language folder, which I have separate libraries for (English comics, German comics, Franco-Belgian comics, etc.):

```
   .
   |-A Clash of Kings
   |---George R.R. Martin's A Clash of Kings - V1 (2017-2019)
   |---George R.R. Martin's A Clash of Kings - V2 (2020-2021)
   |-A Gift for a Ghost (2020)
   |-Alan Moore's Neonomicon (2010-2011)
   |-Alan Moore's The Courtyard (2004)
   |-Aliens - Rescue (2019)
   |-American Gods
   |---American Gods - My Ainsel (2018)
   |---American Gods - Shadows (2017)
   |---American Gods - The Moment of the Storm (2019-2020)
   |-Antarctica (2023-)
   |-Ant Colony (2014)
   |-Are You Listening (2019)
   |-Beautiful Darkness (2014)
   |-Berlin (1996-2018)
   |-Black Cloak (2023)
   |-Black Hole (1995-2004)
   |-Black Magick (2015)
   |-Calvin and Hobbes (1987-1994)
   |-Clementine (2022)
   |-Cyberpunk 2077
   |---Cyberpunk 2077 - Big City Dreams (2022)
   |---Cyberpunk 2077 - Blackout (2022)
   |---Cyberpunk 2077 - Phantom Liberty - Ten of Swords (2023)
   |---Cyberpunk 2077 - Trauma Team (2020)
   |---Cyberpunk 2077 - Where's Johnny (2020)
   |---Cyberpunk 2077 - XOXO (2023-2024)
   |---Cyberpunk 2077 - You Have My Word (2021)
   |---The World of Cyberpunk 2077 (2020)
```

**Comment by maximo1984** [comment]
I opted to go by publisher then title then volumes. As stated in my OG thread, I litereally went to bed with it working, woke up with it not working so I would really like to know what happened. Then you popped up seemingly confirming this is a Kavita problem.
![Screenshot from 2024-03-11 08-17-05](https://github.com/Kareadita/Kavita/assets/40921347/e0444b09-9ed9-4576-85a2-0c9c1a013995)

**Comment by maximo1984** [comment]
Any Updates or ideas what is wrong?

**Comment by Cantello** [comment]
No updates here, I just went on and recreated the library. Shame for the lost reading activities but then again, not terrible. I still have the backup in case more info is needed.

**Comment by majora2007** [comment]
Sorry guys, I have been heads down wrapping up the comic rework stuff. That story includes some big changes to the scanner to make it better. 

I did look at both reported issues and wasn't able to deduce anything wrong, so it is likely some edge case combination or perhaps something in the setup/OS reporting. 

But to my knowledge, both of you setup again from scratch and it worked as expected?

**Comment by maximo1984** [comment]
I have not yet but will do that after update. Thanks for your hard work.

**Comment by Cantello** [comment]
> But to my knowledge, both of you setup again from scratch and it worked as expected?

Yes, it works now just as it did for months before. Don't know what went wrong with my setup.

**Comment by YonierGomez** [comment]
Tuve varios problemas con kavita pero finalmente descubrí cómo funciona, kavita lee son subdirectorios, principalmente había creado un "/book" pero no funcionó, lo que hice fue crear un subdirectorio "/book/allbooks" volví a escanear y aparecieron todos mis archivos.

**Comment by pedroponte** [comment]
Can't seem to have this working properly.

Also had a problem when scanning the first library.

I have recreated the server and it worked with the first library/folder. 

Now, having added new library and folder mounted on

/mnt/pdf/xyz

it can't find any files on the second one.

Are there any logs I can share to allow troubleshooting?
Could this be about file/ownership permissions?

The pdf files are hosted on the host server.
The server is running on a docker engine.
The pdf files are mapped into the /mnt/pdf folder.

TIA

**Comment by majora2007** [comment]
@pedroponte please create your own issue instead of commenting the same thing on 3 different closed issues.
