### ISSUE TITLE
Post Migration Issues

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#2816]
Please comment as much information as possible after you have updated to the Comic Rework nightly. 

In your comment, please include if the issue you are facing is after a force scan on said series/library or not.

**Comment by TheDarkMage** [comment]
On version 0.7.14.9 when force scanning a series that contains files that have a comicinfo file containing a number tag a duplicate volume is created. Based on the log it appears that it thinks that its a new chapter even though it already has been added.
`[Kavita] [2024-03-24 20:56:32.331 -04:00  83] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing My Daughter Left the Nest and Returned an S-Rank Adventurer - Volume 1`
`[Kavita] [2024-03-24 20:56:32.332 -04:00  83] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, My Daughter Left the Nest and Returned an S-Rank Adventurer - Vol 1 Ch 1.0`

**Comment by majora2007** [comment]
@TheDarkMage I believe this should be fixed in v0.7.14.10. Please do let me know.

**Comment by TheDarkMage** [comment]
It's still happening with the same behavior. I even tried deleting the series and re-adding it to see if that would help, but no luck.

**Comment by majora2007** [comment]
Can you give me a bit more information? Are these archives, epub, PDF, etc? What type of library are they in?

**Comment by TheDarkMage** [comment]
These are Manga cbz files that were exported from calibre originally.

**Comment by TheDarkMage** [comment]
I also tried adding the number tag to a non calibre exported cbz file and it produced the same results.

**Comment by majora2007** [comment]
> I also tried adding the number tag to a non calibre exported cbz file and it produced the same results.

Can you check if there is a comicinfo in the files? Calibre doesn't actually write metadata to archives, just to it's "database".

**Comment by TheDarkMage** [comment]
There is, I forgot that I have a plugin that writes the data to the comicinfo file.

**Comment by majora2007** [comment]
Some issues I found myself: 
- [x] /library/1/series/2242 (prod) is being split from the main series for some reason
- [x] Slight memory increase (idle at 225MB vs normal previous of just under 200MB)
- [x] bookmark reporting that marking a Volume 1 as Special (format tag) isn't overriding Volume number.
- [x] Kavita wont be able to find the Chapter when "Volume 1 Chapter 1.0" as internally Range gets overridden to "1" and thus duplicates occur in Kavita.

**Comment by majora2007** [comment]
@TheDarkMage can you provide for me a list of the files (that are causing duplication) and the ComicInfo.xml for each? 

I can't reproduce with non-ComicInfo.xml:
![image](https://github.com/Kareadita/Kavita/assets/735851/6a76ea1d-5888-4362-b1b4-9e6e48dea7d4)

**Comment by TheDarkMage** [comment]
It appears that 7.14.11 has fixed the problem, but in case you still want the info, the file names are
```
My Daughter Left the Nest and Returned an S-Rank Adventurer v01.cbz
My Daughter Left the Nest and Returned an S-Rank Adventurer v02.cbz
My Daughter Left the Nest and Returned an S-Rank Adventurer v03.cbz
```
and here are the comicinfo files renamed to v0#_ComicInfo.xml
[https://drive.google.com/drive/folders/1L7-gwbgh0DuvrrltJ0SJgnZ17pXjob30?usp=sharing](url)

**Comment by majora2007** [comment]
Awesome, glad it got fixed. Pretty positive everything should be working as it did before. I'll leave this issue open for one more week in case anything pops up.

**Comment by TheDarkMage** [comment]
Two things I noticed after updating my main instance from 7.14.3 to 7.14.11. 
First I'm having to delete and re-add some series or a duplicate manga volume still gets made. The original volume shows up as Chapter 1.0 and the duplicate shows up as Chapter 1. I'm assuming this is something that just needs to be checked for in one of the after update migrations that get run e.g. change chapter number from 1.0 to just 1, but I could be wrong. 

Second thing, I noticed that loose leaf chapters are showing up before volumes/chapters in volumes e.g. chapter 41 shows up before volume 1 and when trying to read, chapters jump back to the beginning of the volume instead of to the next volume e.g. instead of vol 1 ch3 to vol1 ch4, it goes to vol1 ch1. These both get fixed after a forced series scan though.

**Comment by majora2007** [comment]
@TheDarkMage are you doing a force scan after updating? The migration does have the work but it does leave some stuff in an in-between state. Then the force scan ensures everything is cleaned up. 

I can't do it automatically on startup as force scans can take hours.

**Comment by TheDarkMage** [comment]
I am doing a force scan after updating, that is what is causing the duplicate volume to get made. 
I took a look at the db, and it looks like this is happening because the range is 1.0 compared to the new volume with a range of 1 as if I manually change the volumes range to 1 then the duplicate doesn't get made, but I could be totally off on this.

As for the second thing, I get that you can't do a force scan automatically. I was more so just letting you know that this was happening, not asking that you do a force scan, sorry if I worded that poorly.

**Comment by majora2007** [comment]
Ahh the 1.0 vs 1 issue was just fixed in the latest nightly (v0.7.14.11). I also saw that as well. 

Oh no, for the force scan, what I meant is that at startup, after the migrations run, I can't necessarily force a scan before the user interacts with the system, hence why it's needed for the user to do a force scan themselves, so the system can cleanup leftover data from the manual migrations. That's all I meant.

**Comment by TheDarkMage** [comment]
Gotcha, I misread your comment, my bad. I just went back and did a full library force scan and it looks like everything is working properly now. Thanks for all your work!

**Comment by majora2007** [comment]
Closing now as no new issues have been reported. Looks like new code is working great.
