### ISSUE TITLE
Koreader Progress Sync

### ISSUE THREAD

**Issue by morillocarlos** [Kareadita/Kavita#3928]
### What happened?

Following the KOReader setup guide leads to a network error with progress sync.

"Something went wrong when syncing prgoress, please check your network connections and try again"

However, if you switch the recommended "custom sync server" address from:
<your-kavita-server>/api/koreader/<your-api-token>
to:
<your-kavita-server>/api/opds/<your-api-token>

The network error resolves, but the Kavita server's progress is NOT updated.

I have no issues with accessing the OPDS catalog as described in the guide.

### What did you expect?

Progress sync with

<your-kavita-server>/api/koreader/<your-api-token>

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.7 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### Relevant log output

```shell

```

### Additional Notes

Running Kavita v0.8.7 in a docker container on a synology nas. Running KOReader on both a Boox Palma and Kobo. KOReader version 2025.04

**Comment by Cducharme84** [comment]
We’re finding folks are having the most success using the koreader endpoint on the nightly from the koreader team rather than base 2025.04, would you mind trying one from their repo to see if that helps?

https://build.koreader.rocks/download/nightly/

**Comment by morillocarlos** [comment]
Thanks for the suggestion. Just updated to latest nightly, 2025.04-161-g70039c9f0_2025-07-15. Still no luck. What nightly are you running?

**Comment by Nebelherr23** [comment]
v2025.04-110-g946638e98_2025-06-03.zip, verified working on a tolino vision 5 and a vision color.

**Comment by morillocarlos** [comment]
Just installed v2025.04-110-g946638e98_2025-06-03 on the Boox Palma, still getting the network error. Should a clean install be done when updating to Kavita 0.8.7? I ran the force scan earlier.

**Comment by scare376** [comment]
when you say a force scan. did you click the force scan button in the library settings? or did you initiate a manual scan from the dropdown on the library

**Comment by morillocarlos** [comment]
Force scan through the library settings: Settings/Server/Libraries/Edit/Force Scan

**Comment by KeePach** [comment]
I'm having the same issue, koreader v.2025.08 and kavita v0.8.7.0,  same message of network error

**Comment by Melon-Bread** [comment]
Same issue on latest KOReader Stable (v.2025.08) & Nightly (v2025.08-57-g28926634d) and kavita v0.8.7.0 (set up using docker instructions in docs.), The korsync works in Calibre & Readest just not with KOReader itself so there is some kind of disconnect going on.

**Comment by majora2007** [comment]
Oops this got missed. I fixed this in the nightly, the next stable will have it working. 

(I'll link to the PR later)

**Comment by majora2007** [comment]
Closed via #4006

**Comment by Melon-Bread** [comment]
> Same issue on latest KOReader Stable (v.2025.08) & Nightly (v2025.08-57-g28926634d) and kavita v0.8.7.0 (set up using docker instructions in docs.), The korsync works in Calibre & Readest just not with KOReader itself so there is some kind of disconnect going on.

This issue still persists even on V0.8.8

**Comment by majora2007** [comment]
> > Same issue on latest KOReader Stable (v.2025.08) & Nightly (v2025.08-57-g28926634d) and kavita v0.8.7.0 (set up using docker instructions in docs.), The korsync works in Calibre & Readest just not with KOReader itself so there is some kind of disconnect going on.
> 
> This issue still persists even on V0.8.8

I validated this on my device on the stable and had it working as expected. Can you provide how you're testing?

**Comment by Melon-Bread** [comment]
I am logging in via KOReader stable with a new api token and then after trying to push or pull in KOReader I get the following error:
"Something went wrong when syncing progress, please check your network connections and try again"


In the logs it states as follows:
"[Kavita] [2025-10-21 13:30:00.539 -04:00  87] [Debug] API.Services.KoreaderService Saving Koreader progress for User (1): /body/DocFragment[56]/body/div/p[36]/text().0

[Kavita] [2025-10-21 13:30:00.540 -04:00  87] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP PUT /api/koreader/<new_api>/syncs/progress responded 400 in 1.6941 ms

[Kavita] [2025-10-21 13:30:15.081 -04:00  57] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/koreader/<new_api>/syncs/progress/ef041b4c1e3a33b88d34c741fbd56718 responded 400 in 5.5832 ms"

I have the same issue regardless of trying on Android, PC, or Pocketbook E-Reader version of KOReader.

**Comment by majora2007** [comment]
Hmm the Kavita logs look correct. I know KOReader just released a stable after I fixed up this, so I can recheck.

**Comment by majora2007** [comment]
v2025.04 is working correctly, there is an open ticket with Koreader about their recent update to opds.
https://github.com/koreader/koreader/issues/14377

**Comment by majora2007** [comment]
I just retested v2025.04 and it seems like it's broken again. I'm not sure how, but Ill look into this.

**Comment by Roshri** [comment]
Can confirm, just tried on a fresh install v2025.04 and it sync doesn't work, it just resets to the first page

**Comment by kkkykin** [comment]
> Can confirm, just tried on a fresh install v2025.04 and it sync doesn't work, it just resets to the first page

If you are pull from kavita, I fix it by this caddy snippet (built with [replace-response](https://github.com/caddyserver/replace-response)) to reverse proxy kavita, goto first page of chapter instead of book:
```caddy
reverse_proxy http://127.0.0.1:5000 {
  header_up Accept-Encoding "identity"
}

@koreaderProgress {
  method GET
  header Accept application/vnd.koreader.v1+json
  path /api/koreader/*/syncs/progress/*
}

replace @koreaderProgress {
  re "(\"progress\":\"/body/DocFragment\[\d+\])/.*\"" "$1.0\""
}
```

Because here always return `/body/div/{lastTag}`, https://github.com/Kareadita/Kavita/blob/f9280f686128ca489322648b4c5485fc76d8eea7/API/Helpers/KoreaderHelper.cs#L111
But koreader can't find this position, so reset to first page of book.

**Comment by majora2007** [comment]
I'm not sure how it worked for me in the past and not now, but I have fixed it once again. It will be in a nightly soon.

**Comment by majora2007** [comment]
I pushed out a new nightly (v0.8.8.6) with enhanced logging around the payload of KOReader and translation Kavita does. Please help me in testing out this build against some of your files and for any issues (aka pull progress sets to cover page), please grab the statements from the logs, with the signature:
`"Converting KOReader progress from {KavitaProgress} to {KOReaderProgress}"`
`"Converting KOReader progress from {ReportedProgress} to {ScopedProgress}"`

**Comment by itsmejoeeey** [comment]
Hi @majora2007, I upgraded to the nightly and am still seeing the issue where pull progress on my book sets to cover page.

Here are the logs as requested for **the erroneous pull**:
```
[Kavita] [2025-11-19 21:04:36.458 +13:00  55] [Debug] API.Services.KoreaderService Converting KOReader progress from id("rw-p_436320-982421337") to id("rw-p_436320-982421337")
[Kavita] [2025-11-19 21:04:36.458 +13:00  55] [Debug] API.Controllers.KoreaderController Koreader response progress for User (2): /body/DocFragment[7]/body/id("rw-p_436320-982421337")
[Kavita] [2025-11-19 21:04:36.458 +13:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/koreader/<token>/syncs/progress/<hash> responded 200 in 1.5639 ms
```

Here are the logs for a successful push from KOReader (works as expected in Kavita):
```
[Kavita] [2025-11-19 21:07:40.598 +13:00  55] [Debug] API.Services.KoreaderService Saving Koreader progress for User (2): /body/DocFragment[7]/body/div/div/p[17]/text().0
[Kavita] [2025-11-19 21:07:40.598 +13:00  55] [Debug] API.Services.KoreaderService Converting KOReader progress from /body/DocFragment[7]/body/div/div/p[17]/text().0 to //html[1]/body/app-root[1]/div[1]/div[1]/div[1]/app-book-reader[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div/div/p[17]/text().0
[Kavita] [2025-11-19 21:07:40.599 +13:00  55] [Debug] API.Services.ReaderService Saving Progress on Series 2, Chapter 3 to Page 6
[Kavita] [2025-11-19 21:07:40.604 +13:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP PUT /api/koreader/<token>/syncs/progress responded 200 in 6.8079 ms
```

Both of these logs are for the same EPUB book.

Let me know if I can provide more information and I'll do my best!

**Comment by majora2007** [comment]
Oops forgot to reopen this. Getting mixed results from testers. I plan to circle back on this after my current branch.

**Comment by voyager** [comment]
@majora2007 what are the chances of this issue resurfacing again? :)
I'm on 0.8.9 running in Docker, did a forced library refresh from the library settings page, have the latest stable KOreader (2025.10) and I'm getting identical error and behavior as @morillocarlos above 🤷‍♂️

`Something went wrong when syncing progress, please check your network connections and try again`

Logging in to the custom /api/koreader/API_KEY URL with my Kavita username works on KOreader on Android, but not the syncing.

I've also tried the `/api/koreader` URL with both my custom domain and local IP:port, no difference.

Another thing I've noticed—while accessing `/api/opds` in a browser returns XML content (catalog), `/api/koreader` returns a 404 page.

**Comment by majora2007** [comment]
@voyager 

First, can you confirm you created a new Auth Key with no expiration and used that? 

Second, `api/koreader` is not the same as opds with `api/opds`. OPDS is how Koreader consumes/browses the data, koreader endpoints are for the login/sync APIs, so they will not return XML. 

The error implies that there is a DNS issue. Do you see the koreader sync request in Kavita's logs when you try to sync? If not, this implies the request isn't hitting your server.

**Comment by Melon-Bread** [comment]
Just wanted to chime in and state that since 0.8.9, after making a new key, & full refresh that KOReader syncing has been working for me no problem across all my devices.

Thank you

**Comment by voyager** [comment]
Thanks @majora2007. I (re)created a new key now (previously I created one called koreader and tried using that one, after the original one didn't work). I was seeing the 400 error in Kavita logs, but now it works. Thanks!
