### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by Jerome2103** [Kareadita/Kavita#748]
When i say, Make a backup 
If he creates a zip, but this one is empty.

I use the newst docker Image ( :lastest)

**Comment by majora2007** [comment]
Hello, so on latest nightly, you make a backup through web ui but there is nothing in it?

**Comment by Jerome2103** [comment]
he has already made a backup, but the backup file is empty.

**Comment by majora2007** [comment]
I have created an issue for this (since yours is missing information). You can subscribe to it if you'd like. 

https://github.com/Kareadita/Kavita/issues/749

**Comment by majora2007** [comment]
This has been fixed and merged. You can pull the latest nightly to validate. If you find it not working, please reopen the issue I linked and leave me a comment.

**Comment by Jerome2103** [comment]
I tested it with the nightly version, but it still doesn't work.

**Comment by majora2007** [comment]
You pulled the latest that was released about an hour ago?

**Comment by Jerome2103** [comment]
Yes

**Comment by majora2007** [comment]
Okay, ill retest on docker.

**Comment by Jerome2103** [comment]
I have commissioned the backup via the setting.
It was version 0.4.11

**Comment by majora2007** [comment]
Okay, I saw the issue. This will be fixed and released later today.
